// Autogenerated by jnigen. DO NOT EDIT!

#include <stdint.h>
#include "dartjni.h"
#include "jni.h"

thread_local JNIEnv* jniEnv;
JniContext* jni;

JniContext* (*context_getter)(void);
JNIEnv* (*env_getter)(void);

void setJniGetters(JniContext* (*cg)(void), JNIEnv* (*eg)(void)) {
  context_getter = cg;
  env_getter = eg;
}

// OverlayInterface
jclass _c_OverlayInterface = NULL;

jmethodID _m_OverlayInterface__addView = NULL;
FFI_PLUGIN_EXPORT
JniResult OverlayInterface__addView(jobject self_) {
  load_env();
  load_class_global_ref(&_c_OverlayInterface, "OverlayInterface");
  if (_c_OverlayInterface == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_OverlayInterface, &_m_OverlayInterface__addView, "addView",
              "()V");
  if (_m_OverlayInterface__addView == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_OverlayInterface__addView);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_OverlayInterface__removeView = NULL;
FFI_PLUGIN_EXPORT
JniResult OverlayInterface__removeView(jobject self_) {
  load_env();
  load_class_global_ref(&_c_OverlayInterface, "OverlayInterface");
  if (_c_OverlayInterface == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_OverlayInterface, &_m_OverlayInterface__removeView,
              "removeView", "()V");
  if (_m_OverlayInterface__removeView == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_OverlayInterface__removeView);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_OverlayInterface__show0 = NULL;
FFI_PLUGIN_EXPORT
JniResult OverlayInterface__show0(jobject self_) {
  load_env();
  load_class_global_ref(&_c_OverlayInterface, "OverlayInterface");
  if (_c_OverlayInterface == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_OverlayInterface, &_m_OverlayInterface__show0, "show", "()V");
  if (_m_OverlayInterface__show0 == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_OverlayInterface__show0);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_OverlayInterface__hide0 = NULL;
FFI_PLUGIN_EXPORT
JniResult OverlayInterface__hide0(jobject self_) {
  load_env();
  load_class_global_ref(&_c_OverlayInterface, "OverlayInterface");
  if (_c_OverlayInterface == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_OverlayInterface, &_m_OverlayInterface__hide0, "hide", "()V");
  if (_m_OverlayInterface__hide0 == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_OverlayInterface__hide0);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_OverlayInterface__getLayoutParams = NULL;
FFI_PLUGIN_EXPORT
JniResult OverlayInterface__getLayoutParams(jobject self_) {
  load_env();
  load_class_global_ref(&_c_OverlayInterface, "OverlayInterface");
  if (_c_OverlayInterface == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_OverlayInterface, &_m_OverlayInterface__getLayoutParams,
              "getLayoutParams", "()Landroid/view/WindowManager$LayoutParams;");
  if (_m_OverlayInterface__getLayoutParams == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->CallObjectMethod(
      jniEnv, self_, _m_OverlayInterface__getLayoutParams);
  return to_global_ref_result(_result);
}

jmethodID _m_OverlayInterface__updateLayoutParams = NULL;
FFI_PLUGIN_EXPORT
JniResult OverlayInterface__updateLayoutParams(jobject self_,
                                               jobject layoutParams) {
  load_env();
  load_class_global_ref(&_c_OverlayInterface, "OverlayInterface");
  if (_c_OverlayInterface == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_OverlayInterface, &_m_OverlayInterface__updateLayoutParams,
              "updateLayoutParams",
              "(Landroid/view/WindowManager$LayoutParams;)V");
  if (_m_OverlayInterface__updateLayoutParams == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(
      jniEnv, self_, _m_OverlayInterface__updateLayoutParams, layoutParams);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_OverlayInterface__reportSize = NULL;
FFI_PLUGIN_EXPORT
JniResult OverlayInterface__reportSize(jobject self_, int32_t i, int32_t i1) {
  load_env();
  load_class_global_ref(&_c_OverlayInterface, "OverlayInterface");
  if (_c_OverlayInterface == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_OverlayInterface, &_m_OverlayInterface__reportSize,
              "reportSize", "(II)V");
  if (_m_OverlayInterface__reportSize == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_OverlayInterface__reportSize, i,
                            i1);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

// OverlayManager
jclass _c_OverlayManager = NULL;

jmethodID _m_OverlayManager__getOverlay = NULL;
FFI_PLUGIN_EXPORT
JniResult OverlayManager__getOverlay(jobject self_, jobject string) {
  load_env();
  load_class_global_ref(&_c_OverlayManager, "OverlayManager");
  if (_c_OverlayManager == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_OverlayManager, &_m_OverlayManager__getOverlay, "getOverlay",
              "(Ljava/lang/String;)LOverlayInterface;");
  if (_m_OverlayManager__getOverlay == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->CallObjectMethod(
      jniEnv, self_, _m_OverlayManager__getOverlay, string);
  return to_global_ref_result(_result);
}

jmethodID _m_OverlayManager__hasOverlay = NULL;
FFI_PLUGIN_EXPORT
JniResult OverlayManager__hasOverlay(jobject self_, jobject string) {
  load_env();
  load_class_global_ref(&_c_OverlayManager, "OverlayManager");
  if (_c_OverlayManager == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_OverlayManager, &_m_OverlayManager__hasOverlay, "hasOverlay",
              "(Ljava/lang/String;)Z");
  if (_m_OverlayManager__hasOverlay == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  uint8_t _result = (*jniEnv)->CallBooleanMethod(
      jniEnv, self_, _m_OverlayManager__hasOverlay, string);
  return (JniResult){.value = {.z = _result}, .exception = check_exception()};
}

jmethodID _m_OverlayManager__setOverlay = NULL;
FFI_PLUGIN_EXPORT
JniResult OverlayManager__setOverlay(jobject self_,
                                     jobject string,
                                     jobject overlayInterface) {
  load_env();
  load_class_global_ref(&_c_OverlayManager, "OverlayManager");
  if (_c_OverlayManager == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_OverlayManager, &_m_OverlayManager__setOverlay, "setOverlay",
              "(Ljava/lang/String;LOverlayInterface;)V");
  if (_m_OverlayManager__setOverlay == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_OverlayManager__setOverlay,
                            string, overlayInterface);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jfieldID _f_OverlayManager__INSTANCE = NULL;
FFI_PLUGIN_EXPORT
JniResult get_OverlayManager__INSTANCE() {
  load_env();
  load_class_global_ref(&_c_OverlayManager, "OverlayManager");
  if (_c_OverlayManager == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_static_field(_c_OverlayManager, &_f_OverlayManager__INSTANCE, "INSTANCE",
                    "LOverlayManager;");
  jobject _result = (*jniEnv)->GetStaticObjectField(
      jniEnv, _c_OverlayManager, _f_OverlayManager__INSTANCE);
  return to_global_ref_result(_result);
}
